import { useState } from 'react';
import { Card, Button, Badge } from './ui';
import { 
  FileText, 
  Copy, 
  Check, 
  Download, 
  X, 
  ShieldCheck, 
  Clock, 
  AlertTriangle 
} from './ui';

interface PostMortemExportModalProps {
  isOpen: boolean;
  onClose: () => void;
  incident: any;
  events?: any[];
  rootCauseReport?: any;
  patchReview?: any;
}

export function PostMortemExportModal({
  isOpen,
  onClose,
  incident,
  events = [],
  rootCauseReport,
  patchReview,
}: PostMortemExportModalProps) {
  const [copied, setCopied] = useState(false);

  if (!isOpen || !incident) return null;

  // Generate clean Post-Mortem Markdown content
  const generateMarkdown = (): string => {
    const timestamp = new Date().toISOString();
    const eventLines = (events || [])
      .slice()
      .sort((a, b) => new Date(a.createdAt).getTime() - new Date(b.createdAt).getTime())
      .map(
        (e) =>
          `- **${new Date(e.createdAt).toLocaleTimeString()}** [${e.stage.toUpperCase()} - ${e.status.toUpperCase()}]: ${e.summary}${e.detail ? `\n  - *Detail*: ${e.detail}` : ''}`
      )
      .join('\n');

    const claimsList = (rootCauseReport?.claims || [])
      .map((c: any, i: number) => `${i + 1}. ${c.text} *(Evidence: ${c.evidenceIds?.join(', ') || 'N/A'})*`)
      .join('\n');

    return `# Incident Post-Mortem: ${incident.title}

**Incident ID:** \`${incident.id}\`  
**Service Affected:** \`${incident.service}\`  
**Severity:** **${incident.severity?.toUpperCase()}**  
**Current Status:** \`${incident.status}\`  
**Report Generated:** ${timestamp}  
**Inference Engine:** \`${rootCauseReport?.modelName || 'nemotron-4-340b-instruct'}\` (${rootCauseReport?.inferenceMode === 'demo' ? 'Controlled Demo' : 'Live Inference'})

---

## 1. Executive Summary & Impact

- **User Impact:** ${incident.impactSummary || 'N/A'}
- **Alert Trigger:** ${incident.alertContext || 'N/A'}
- **Root Cause Summary:** ${rootCauseReport?.summary || 'Investigation in progress'}
- **Confidence Assessment:** ${(rootCauseReport?.confidence ? rootCauseReport.confidence * 100 : 0).toFixed(0)}%

---

## 2. Investigation Timeline & Milestones

${eventLines || '- No timeline events recorded.'}

---

## 3. Evidence-Backed Diagnosis

${claimsList ? `### Key Diagnostic Claims\n\n${claimsList}` : 'No diagnostic claims generated.'}

${rootCauseReport?.limitations ? `### Diagnostic Limitations\n\n> ⚠ ${rootCauseReport.limitations}` : ''}

---

## 4. Proposed Remediation & Verification

${patchReview ? `### Code Repair Summary\n\n${patchReview.summary}\n\n**Files Modified:**\n${(patchReview.filesChanged || []).map((f: string) => `- \`${f}\``).join('\n') || '- None'}\n\n### Unified Diff\n\n\`\`\`diff\n${patchReview.diff}\n\`\`\`\n\n### Test Verification Status\n\n- **Verification Result:** \`${patchReview.verificationStatus?.toUpperCase()}\`\n- **Verification Log:**\n\`\`\`text\n${patchReview.verificationOutput || 'No verification log available.'}\n\`\`\`` : 'No repair proposal generated.'}

---

## 5. Human Approval Gate & Safety Sign-Off

> **Policy Requirement:** Automated patch deployment is strictly prohibited. Human reviewer sign-off is required prior to release.

- **Approval Decision:** \`${patchReview?.approvalStatus?.toUpperCase() || 'PENDING'}\`
- **Reviewer ID:** \`${patchReview?.reviewerId || 'Pending Human Review'}\`
- **Reviewed At:** ${patchReview?.reviewedAt ? new Date(patchReview.reviewedAt).toISOString() : 'Pending'}

---
*Report generated by Incident Commander — Nebius x NVIDIA AI Outage Operations Platform*
`;
  };

  const markdownContent = generateMarkdown();

  const handleCopy = () => {
    navigator.clipboard.writeText(markdownContent);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = () => {
    const blob = new Blob([markdownContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `incident-postmortem-${incident.id.slice(0, 8)}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/80 backdrop-blur-sm animate-fade-in">
      <Card className="w-full max-w-3xl max-h-[90vh] bg-graphite-950 border-graphite-800 flex flex-col shadow-2xl shadow-violet-950/20">
        {/* Modal Header */}
        <div className="flex items-center justify-between p-4 border-b border-graphite-800">
          <div className="flex items-center gap-2">
            <div className="p-2 rounded-lg bg-violet-500/10 text-violet-400">
              <FileText className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-sm font-semibold text-white">Incident Post-Mortem Report</h3>
              <p className="text-xs text-graphite-400 font-mono">
                INC-{incident.id.slice(0, 8)} • Ready for download / distribution
              </p>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <Button
              variant="secondary"
              size="sm"
              className="gap-1.5 text-xs text-graphite-300 border border-graphite-700 hover:bg-graphite-800"
              onClick={handleCopy}
            >
              {copied ? <Check className="w-3.5 h-3.5 text-status-green-400" /> : <Copy className="w-3.5 h-3.5" />}
              {copied ? 'Copied' : 'Copy Markdown'}
            </Button>

            <Button
              variant="primary"
              size="sm"
              className="gap-1.5 text-xs"
              onClick={handleDownload}
            >
              <Download className="w-3.5 h-3.5" />
              Download .md
            </Button>

            <Button
              variant="ghost"
              size="icon"
              className="text-graphite-400 hover:text-white"
              onClick={onClose}
            >
              <X className="w-5 h-5" />
            </Button>
          </div>
        </div>

        {/* Modal Body Preview */}
        <div className="flex-1 overflow-y-auto p-4 bg-graphite-900/60 font-mono text-xs text-graphite-200">
          <pre className="whitespace-pre-wrap break-words leading-relaxed">
            {markdownContent}
          </pre>
        </div>

        {/* Modal Footer */}
        <div className="p-3 border-t border-graphite-800 bg-graphite-950 flex items-center justify-between text-xs text-graphite-500 font-mono">
          <span>Format: Markdown (.md)</span>
          <span className="text-violet-400 flex items-center gap-1">
            <ShieldCheck className="w-3.5 h-3.5" />
            Evidence-Backed & Human-Gated Audit Report
          </span>
        </div>
      </Card>
    </div>
  );
}
